config setup
    charondebug="ike 2, knl 2, cfg 2"

conn site-to-site
    auto=start
    keyexchange=ikev2

    left=100.64.10.10
    leftsubnet=10.111.10.0/24

    right=100.64.10.20
    rightsubnet=10.222.20.0/24

    authby=psk

    ike=aes256-sha256-modp2048!
    esp=aes256-sha256!
